services:
  - type: web
    name: zetra-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false && npx tsc --project tsconfig.server.json
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TURN_SERVER_URL
        value: turn:openrelay.metered.ca:80
      - key: TURN_SERVER_USERNAME
        value: openrelayproject
      - key: TURN_SERVER_CREDENTIAL
        value: openrelayproject
